### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by YanaseHiroki** [YanaseHiroki/furima_28335#11]
# 【依頼】フリマアプリ挙動確認  
挙動確認をしていただけますよう、よろしくお願いします！
## what
テストアカウントなどです！
項目 | 情報
-- | --
自身のフリマアプリのURL | https://furima-28335.herokuapp.com/
Basic認証のID |  administrator
Basic認証のパスワード |  31415926535
出品者用のメールアドレス | sample@sample.com
出品者用のパスワード | sample123
購入者用のメールアドレス | test@test.com
購入者用のパスワード | test123
購入用カードの番号 | 4242424242424242
購入用カードの期限 | 2024年12月 ( 12 24 の順に入力)
購入用カードのセキュリティコード | 123

## why
最終課題のフリマアプリ挙動確認のためです！

**Comment by mo1015** [comment]
確認でき次第、再度フォームの提出をお願いいたします！
https://forms.gle/dYuR1wjeHepbEhU7A

フォームご提出後、改めて確認させていただきます！

**Comment by YanaseHiroki** [comment]
依頼を編集して、フォームを再提出させていただきました！
お手数ですが、挙動確認をしていただけますようよろしくお願いします！

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by YanaseHiroki** [comment]
LGTMをいただきありがとうございます！
今後、追加実装などに取り組んでいきます！
